version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nguynmjnk
      POSTGRES_PASSWORD: minh2004
      POSTGRES_DB: iris_authentication
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: