# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_camera = QtWidgets.QWidget(self.centralwidget)
        self.widget_camera.setGeometry(QtCore.QRect(90, 160, 591, 351))
        self.widget_camera.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.widget_camera.setObjectName("widget_camera")
        self.label = QtWidgets.QLabel(self.widget_camera)
        self.label.setGeometry(QtCore.QRect(190, 70, 201, 181))
        self.label.setStyleSheet("border: 2px solid black ;\n"
"border-color: rgb(255, 0, 0);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_capture = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_capture.setGeometry(QtCore.QRect(160, 40, 131, 61))
        self.pushButton_capture.setStyleSheet("background-color: rgb(255, 255, 255); font-size:14pt\n"
"")
        self.pushButton_capture.setObjectName("pushButton_capture")
        self.pushButton_2_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2_save.setGeometry(QtCore.QRect(480, 40, 191, 61))
        self.pushButton_2_save.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 14pt;")
        self.pushButton_2_save.setObjectName("pushButton_2_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_capture.setText(_translate("MainWindow", "Capture"))
        self.pushButton_2_save.setText(_translate("MainWindow", "Save and continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
